### ISSUE TITLE
build against LLVM 3.5

### ISSUE THREAD

**Issue by rekado** [digego/extempore#182]
I'm packaging Extempore for GNU Guix (it's written in Scheme), and I only have LLVM 3.5 or 3.6 available here, so I thought I'd patch the sources to make it build.  I applied the following patch and managed to compile with `all.bash`:

~~~
--- a/src/EXTLLVM.cpp	2015-07-18 18:01:06.621089828 +0200
+++ b/src/EXTLLVM.cpp	2015-07-18 18:00:26.651901727 +0200
@@ -71,7 +71,7 @@
 
 //#include "llvm/Analysis/DebugInfo.h"
 //#include "llvm/Analysis/Verifier.h"
-#include "llvm/Assembly/Parser.h"
+#include "llvm/AsmParser/Parser.h"
 #include "llvm/IR/LLVMContext.h"
 #include "llvm/IR/CallingConv.h"
 #include "llvm/IR/Module.h"
@@ -1557,7 +1557,7 @@
 	    //EE = llvm::EngineBuilder(M).create();
 	    PM = new llvm::PassManager();
 	    //PM->add(new llvm::TargetData(*EE->getTargetData()));
-      PM->add(new llvm::DataLayout(*(EE->getDataLayout())));
+      PM->add(new llvm::DataLayoutPass(*(EE->getDataLayout())));
 
       PM->add(llvm::createBasicAliasAnalysisPass());   //new   
       // promote allocs to register

--- a/src/SchemeFFI.cpp	2015-07-18 17:59:56.775013624 +0200
+++ b/src/SchemeFFI.cpp	2015-07-18 17:55:44.887526162 +0200
@@ -88,7 +88,7 @@
 #endif
 
 /////////////////////// llvm includes
-#include "llvm/Assembly/Parser.h"
+#include "llvm/AsmParser/Parser.h"
 #include "llvm/IR/LLVMContext.h"
 #include "llvm/IR/CallingConv.h"
 #include "llvm/IR/Module.h"
@@ -105,7 +105,9 @@
 #include "llvm/Support/ManagedStatic.h"
 #include "llvm/Support/raw_ostream.h"
+#include "llvm/Support/FileSystem.h"
 #include "llvm/Support/SourceMgr.h"
-#include "llvm/Analysis/Verifier.h"
+#include "llvm/IR/Verifier.h"
+#include "llvm-c/Analysis.h"
 //#include "llvm/Target/TargetData.h"
 #include "llvm/LinkAllPasses.h"
 #include "llvm/PassManager.h"
@@ -1992,7 +1991,7 @@
       }else{
       if (extemp::EXTLLVM::VERIFY_COMPILES) {
         std::string Err;
-        if (verifyModule(*M, ReturnStatusAction, &Err)) {
+        if (verifyModule(*M)) {
           printf("%s\n%s","Parsed, but not valid!\n",Err.c_str());
 #ifndef EXT_MCJIT        
           if(num_of_funcs != M->getFunctionList().size()) {
@@ -2264,10 +2263,10 @@
 	}			
         
         char* filename = string_value(pair_car(args));
         std::string errinfo;
-	llvm::raw_fd_ostream ss(filename,errinfo);
+	llvm::raw_fd_ostream ss(filename,errinfo,sys::fs::F_None);
         if(errinfo.length()>0) {
           std::cout << errinfo << std::endl;
           return _sc->F;
         }
         llvm::WriteBitcodeToFile(M,ss);
~~~

However, I cannot seem to compile the stdlib:

~~~
Evaluating expression: (sys:precomp:compile-xtm-file "libs/" #t #t #t)

SetValue:  NaNf >>> float
SetValue:  NaNd >>> double
Extempore: <string>:46:18: error: '@llvm_zone_malloc' defined with type 'i8* (%mzone*, i64)*'
%dat9 = call i8* @llvm_zone_malloc(%mzone* %zone8, i64 4)
                 ^

Compiler Error  compiler failed
~~~

I've built it and run the executable on a x86_64 system.  Unfortunately, I have no idea what the error tries to tell me.

**Comment by benswift** [comment]
Cool, I've alwauys thought that the Nix approach to package management
was a cool one, although I've never dabbled in it myself.

Thanks for the patch, but I should mention that on the `dev` branch
we've got experimental support for using the MCJIT backend, since the
old JIT is deprecated in 3.4/3.5 and removed completely in 3.6 (as you
probably noticed). You can try it yourself if you're on `dev` with
`./all.bash -DEXT_MCJIT`

Suffice to say, MCJIT is the way forward, so we should really land the
patch against that code. Then we can upgrade to 3.6
and beyond, while still supporting the legacy option with 3.4.

Are you willing to swizzle the patch around to build against llvm 3.6 on
`dev` behind the (`#ifdef EXT_MCJIT`) guards?

How does that sound? Sorry that it's not clearer about the `dev` branch
and MCJIT support in the docs - we're just in flux at the moment as Andy
is away. There will be a giant "merge of doom" in a month or so, but
until then I'm using the `dev` branch as my daily driver.

**Comment by rekado** [comment]
> Cool, I've alwauys thought that the Nix approach to package management
> was a cool one, although I've never dabbled in it myself.

Guix greatly simplifies software management and packaging (at the cost
of figuring out the minimal environment needed to build a piece of
software).  Whenever I want to try out some new software I begin by
writing a package for Guix.

> Thanks for the patch, but I should mention that on the `dev` branch
> we've got experimental support for using the MCJIT backend, since the
> old JIT is deprecated in 3.4/3.5 and removed completely in 3.6 (as you
> probably noticed). You can try it yourself if you're on `dev` with
> `./all.bash -DEXT_MCJIT`

That’s great!  I’ll give it a try.

**Comment by benswift** [comment]
Since we're now building against LLVM 3.7.0 on all platforms in master, I'm gonna close this one.
