### ISSUE TITLE
Support prefix for core libs

### ISSUE THREAD

**Issue by rekado** [digego/extempore#183]
I'm (still) packaging Extempore for GNU Guix and in the absence of an "install" target had to come up with locations for the binary, the libs, examples and so on.

In my package recipe I'm copying the files like this:

- "extempore" to `$prefix/bin/extempore`
- "runtime" to `$prefix/lib/extempore/runtime`
- "examples" to `$prefix/share/extempore/examples`
- "extras" to `$prefix/share/extempore/extras`
- "libs" to `$prefix/lib/extempore/libs`
- Elisp files to `$prefix/share/emacs/site-elisp`

To make this work I had to patch `src/Extempore.cpp` and `extras/extempore.el` to use `$prefix/lib/extempore/runtime` as the default path for the runtime rather than a directory relative to the binary.

But still I'm having a problem with actually using any of the core libs because they include snippets like this (e.g. in `libs/core/instruments.xtm`):

    (sys:load "libs/core/audio_dsp.xtm")

`sys:load` expects a path and the core libs just assume that `extempore` is run from a directory which contains a `libs` directory.  It would be nice if all these relative references to other core libs would be relative to a prefix which could be specified at configure/build time.

This would make it much easier to package and install Extempore.

Would you be willing to accept patches to this effect?

**Comment by benswift** [comment]
Hi Rekado

Thanks for your work on this. I should add that currently the `dev`
branch has experimental cmake support, which may make your life easier.
The dev branch will become the release at some point.

> I'm (still) packaging Extempore for GNU Guix and in the absence of an "install" target had to come up with locations for the binary, the libs, examples and so on.
>
> In my package recipe I'm copying the files like this:
>
> - "extempore" to `$prefix/bin/extempore`
> - "runtime" to `$prefix/lib/extempore/runtime`
> - "examples" to `$prefix/share/extempore/examples`
> - "extras" to `$prefix/share/extempore/extras`
> - "libs" to `$prefix/lib/extempore/libs`
> - Elisp files to `$prefix/share/emacs/site-elisp`
>
> To make this work I had to patch `src/Extempore.cpp` and `extras/extempore.el` to use `$prefix/lib/extempore/runtime` as the default path for the runtime rather than a directory relative to the binary.

There is a `--runtime` option to pass to Extempore at start-up which
allows you to specify the path to the `runtime` dir.  But it doesn't
solve the `sys:load` problem you describe below, so I agree that a
better solution needs to be found.

> But still I'm having a problem with actually using any of the core libs because they include snippets like this (e.g. in `libs/core/instruments.xtm`):
>
>     (sys:load "libs/core/audio_dsp.xtm")
>
> `sys:load` expects a path and the core libs just assume that
> `extempore` is run from a directory which contains a `libs` directory.  

Yeah, in general it assumes that `extempore` is run from the top-level
directory in the Extempore source code.

> It would be nice if all these relative references to other core libs would be relative to a prefix which could be specified at configure/build time.

Yes, I agree.  It doesn't even require a build-time flag, since
`sys:load`, `sys:load-dylib` and friends are acually just Scheme
functions which are loaded at startup, so the paths could be determined
at runtime.

> This would make it much easier to package and install Extempore.
>
> Would you be willing to accept patches to this effect?

@digego is Extempore's BDFL, so I'll wait for him to weigh in on this.
But I do want to say thanks for taking the time to investigate - I
appreciate it.  There are some things about Extempore which reflect the
fact that it's still very much an alpha project, written by folks either
in their spare time or as part of academic jobs where software polish
isn't one of the KPIs :) So thanks for your understanding with that.

What do you reckon, @digego?

P.S. remember to check out the `cmake` support on `dev` and see if it
helps - or at least remember that if you have to make changes then they
should work with that option as well.

**Comment by digego** [comment]
Yes, it would be great to get away from the current dependence on the
extempore CWD.  Let's have a think about the nicest way to do this.  Just
keep in mind that whatever solution we agree upon needs to work equally
well on osx, linux and importantly windows!

**Comment by rekado** [comment]
With CMake as a configuration system it would be easy to define a library prefix and pre-process the core lib sources at configure time.  The core lib sources would be replaced with "templates" that contain a placeholder variable that is replaced with the configured value by CMake.  The result would be core lib sources containing absolute paths when `(sys:load ...)` is used, e.g. `(sys:load "/prefix/path/to/libs/core/audio_dsp.xtm")` for a library prefix of `/prefix/path/to/`.

An alternative would be to make `(sys:load ...)` work with paths relative to the calling site and change the core libs such that they only reference other files relative to their current location, e.g. `(sys:load "audio_dsp.xtm")` in the example above, rather than `(sys:load "libs/core/audio_dsp.xtm")`.

**Comment by benswift** [comment]
I guess there are two issues here:

1. where do we put the various parts of the Extempore tarball (the
executable, the libs/ and examples/ subdirs, etc.) for packaging?  Do we
keep it as is (i.e. everything in a shared root dir), or do we try and
make it a bit more FHS-y (e.g. binary in /usr/local/bin, libs and
examples in /usr/local/share or opt/ or something like that)

2. Once we've decided on 1, how should we tell `sys:load` where to look?
Via a compile-time template, or by creating a "path" of sorts for
sys:load (which may be modified at run-time) to tell it where to look,
and in what order?

For 1., I think I lean towards splitting them up and putting them in
"expected" places, so something like:

extempore in /usr/local/bin
{libs,examples,tests,extras} in /usr/local/share/extempore/{libs,examples,tests,extras}

Then, on windows, replace /usr/local with C:\AppData (which seems to be
the equivalent, as far as I can tell [0]).

Obviously, with Cmake you can override the prefix anyway, so power users
can fill their boots.

This option has the benefit that `extempore` will be on the ``$PATH,
although it means that we have to put some work into point 2. above to
make sure that the `sys:load` calls all still work.  I think it's good to
still have the full `libs/external/libfoo.xtm` path, with the caveat
that `sys:load` should be smart enough to look in `$PREFIX/libs/external`
for the file.

[0] http://windows.microsoft.com/en-us/windows-8/what-appdata-folder

**Comment by rekado** [comment]
I agree.

Re 1: I think Extempore's build system should permit overriding of not just a "master" prefix, but also individual paths for documentation/examples, bindir, and libs, with the defaults set to what you suggested.

Re 2: if `sys:load` were modified to take the "full" relative path `libs/external/libfoo.xtm`, how would a user specify a path relative to the current working directory then?  By prefixing with `./`?

**Comment by benswift** [comment]
Hi rekado

Thanks for the input - I should just mention that @digego is away at the
moment and so might not weigh in straight away.

**Comment by digego** [comment]
1. Multiple path lookups is fine by me - don't forget a path for assets.
In fact we should support arbitrary lists really (see below) - a list for
lib paths, a list for asset paths and possibly a list for examples.

2. sys:load should continue to work as normal (i.e. take both full and
relative paths - relative to current working directory).  Additionally we
can then add support to make sys:load check in other locations if no valid
file is found.  So first we check to see if a file exists at the full or
relative path spec'd by the user.  If no valid file is found we skip
through the list of 'extra' directories to see if anything valid exists at
any of those paths - in some suitable order.  Basically the same kind of
thing as LD_LIBRARY_PATH.

Should be a simple enough change.

Cheers,
Andrew.

p.s. please don't change scheme's 'load' function (i.e. only support the
'extra' path lookups in sys:load).

**Comment by rekado** [comment]
Okay, I'll try to work on this once I get Extempore to work with LLVM 3.6.

**Comment by rekado** [comment]
(I cannot seem to build/link the patched version of LLVM 3.6 on my laptop, probably for lack of resources, so I'll try to make these changes "blindly".)

**Comment by benswift** [comment]
Yeah, building LLVM is a bit of a resource hog.  I have a beefy Linux
box here I can test patches on - let me know when I can help out. Also,
remember to patch the `dev` branch.

Thanks mate.

**Comment by rekado** [comment]
> So first we check to see if a file exists at the full or relative path spec'd by the user. If no valid file is found we skip through the list of 'extra' directories to see if anything valid exists at any of those paths - in some suitable order.

This may lead to problems as `sys:load` is used in the libraries with paths relative to the *executable's* current directory.  If `sys:load` were changed to only search for other paths if the specified file cannot be found relative to the current directory (and not relative to the file calling `sys:load`) the core libraries would be broken if `extempore` were run in a directory containing a file at `libs/core/std.xtm`.

This can be avoided if all instances of `(sys:load "libs/core/...")` in the libs directory were changed to point to the location relative to the file issuing the call to `sys:load`, thus ensuring that the intended file would always be found if it is loaded by one the core lib files.

This would make all of the `libs` directory relocatable.  We'd only have to make sure that the runtime knows where to look for `libs`.  *That* could be achieved with the list of lookup paths that you suggested.  But this requires that the cross-file references in `libs` are internally consistent.

**Comment by benswift** [comment]
So I guess the issue is that there are two things we need to find:

1. the `extempore` executable (e.g. in `/usr/local/bin`)
2. everything else (i.e. `runtime`, `libs`, `examples`, `assets`, `extras`), which it makes sense to have together in some top-level directory such as `/usr/local/share/extempore`

Now, 1. (the `extempore` binary) needs to know where 2. is, and the
items in 2. need to know where they are relative to each other (e.g. so
that examples can reference libs).

Currently, this has been achieved by running `extempore` in the
top-level dir where the various 2. subfolders are, but this has problems
(`extempore` isn't on the `$PATH` for example).

Is the simplest solution that we have a `*extempore-share-path*`
variable which is known to the binary (possibly through a CMAKE
template), and can possibly be overridden with a CLI flag (as we do
currently with the `--runtime` option, see `./extempore --help` for more
info).

Then, a call to `(sys:load "libs/core/mylib.xtm")` will look (in order):

1. `(string-append *extempore-share-path* "/" "libs/core/mylib.xtm")`
2. `(string-append *extempore-bin-dir* "/" "libs/core/mylib.xtm")` (i.e. where the `extempore` binary is running)
3. `libs/core/mylib.xtm` (i.e. full path)

This way, the existing libs (which other libs with paths relative to
`*extempore-share-path*`) will still work unmodified.

Thoughts, @digego?

**Comment by benswift** [comment]
This is all working now - set to `/usr/local/share/extempore` by default on OSX/Linux.  See INSTALL.md for details.
