### ISSUE TITLE
Debug build fails (typo?)

### ISSUE THREAD

**Issue by jkroll20** [digego/extempore#277]
When trying to build with Debug configuration:

```
sudo checkinstall --backup=no --pkgname=extempore --pkgversion=1234-debug make VERBOSE=1 -j4 install
```

Tries to copy 'libassimp.so' which isn't there:

```
[100%] moving shared libs into /home/johannesk/src/extempore/libs/platform-shlibs
cd /home/johannesk/src/extempore/cmake-build-debug/deps-install/lib && /usr/bin/cmake -E make_directory /home/johannesk/src/extempore/libs/platform-shlibs
cd /home/johannesk/src/extempore/cmake-build-debug/deps-install/lib && /usr/bin/cmake -E copy libassimp.so /home/johannesk/src/extempore/libs/platform-shlibs
Error copying file "libassimp.so" to "/home/johannesk/src/extempore/libs/platform-shlibs".
CMakeFiles/extended_deps.dir/build.make:57: recipe for target 'CMakeFiles/extended_deps' failed
make[2]: *** [CMakeFiles/extended_deps] Error 1
make[2]: Leaving directory '/home/johannesk/src/extempore/cmake-build-debug'
CMakeFiles/Makefile2:889: recipe for target 'CMakeFiles/extended_deps.dir/all' failed
make[1]: *** [CMakeFiles/extended_deps.dir/all] Error 2
make[1]: Leaving directory '/home/johannesk/src/extempore/cmake-build-debug'
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

'libassimp**d**.so' exists.

**Comment by benswift** [comment]
I've pushed up a fix for this in ae805f6, so that the libassimp.so will get the same name under both configurations. Having said that, there's a good chance that *using* the assimp library will crash due to struct layout issues - we manually map the assimp classes into xtlang named types, but it's fragile and we prioritise getting it working for the Release config.

Sorry if this is unsatisfying - I feel your pain. It's just part of the impedance mismatch with externally-compiled object files and their dynamic interactive use in Extempore.

**Comment by jkroll20** [comment]
I see. It's better than no debug build at all, thanks.

**Comment by benswift** [comment]
Yep. Slightly :)

Closes GH-277
