### ISSUE TITLE
New min cmake version might be needed

### ISSUE THREAD

**Issue by azimut** [digego/extempore#305]
Due: https://github.com/digego/extempore/blob/624309ff1f3a73c688dee5e00f2800e0c3eca76e/CMakeLists.txt#L16

It looks to me that the min version required to compile master is 3.9 I think it need to be reflected on the docs or on the cmake_minimum_required()

https://cmake.org/cmake/help/git-stage/manual/cmake-policies.7.html

Feel free to close If I a wrong.

**Comment by benswift** [comment]
Hmm. That policy isn't 100% necessary - I was just trying to get rid of the warning. Since 3.9 is only 6months old, I think it's a bit too new to force folks onto. So I've removed the policy altogether in e2e5dcd632702b7f44b384b8bc6780ef8e619a3f - will revisit this later when 3.9 is a bit easier to enforce as a minimum. Thanks.
