### ISSUE TITLE
Better solution for DSP 

### ISSUE THREAD

**Issue by bradrn** [digego/extempore#381]
Currently, the sharedsystem is _very_ useful if I just want to play around a bit with Extempore, since I can just load it and not worry about defining DSP, instruments etc. However, it has one significant problem: I can’t define any new instruments! For instance, let’s say I want to make an `fmsynth`: `(make-instrument mysynth fmsynth)`. Now it’s easy enough to adapt the code from `sharedsystem/audiosetup.xtm` to do DSP for `mysynth`:

```
(bind-func mydsp:DSP
  (let ((load 0.0)
        (total 0.0)
        (tmp 0.0)
        (out 0.0)
        (second SR))
    (lambda (in time chan dat)
      (if (< chan 2)
          (begin
            (set! tmp (clock_clock))
            (set! out (mysynth in time chan dat))
            (set! total (+ total (- (clock_clock) tmp)))
            (if (and (= (% time second) 0) (= chan 0))
                (begin
                  (set! load total)
                  (set! total 0.0)))
            out)
          0.0))))
```

And add an extra sixth channel to the reverb effect:

```
(bind-func dspmt:DSPMT
  (let ((reverb (creverb_st_c "assets/ir/minsterl.aif"
                              "assets/ir/minsterr.aif"))
        (r1 0.0)
        (r2 0.0)
        (r3 0.0)
        (r4 0.0)
        (r5 0.0)
        (r6 0.0)
        (rev 0.0)
        (gain 2.0)
        (rmix 1.0))
    (lambda (in time chan dat)
      (if (> rmix 0.001)
          (set! rev (reverb chan
                        (+ (* r1 (pref in 0))
                           (* r2 (pref in 1))
                           (* r3 (pref in 2))
                           (* r4 (pref in 3))
                           (* r5 (pref in 4))
                           (* r6 (pref in 4)))
                        0.0 1.0)))
      (+  (* rmix rev)
          (* gain
            (+ (pref in 0)
               (pref in 1)
               (pref in 2)
               (* 2.0 (pref in 3))
               (* 2.0 (pref in 4))))))))
```

Now, the last thing I need to do is change the final `(dsp:set! #f dspmt dsp1 dsp2 dsp3 dsp4 dsp5)` to `(dsp:set! #f dspmt dsp1 dsp2 dsp3 dsp4 dsp5 mydsp)`. But when I try this, I get an error: ‘You can only set the DSP callback once, but you can re-define that function as often as you like’. This message seems pretty clear to me: I can’t add my `mydsp` function to the `dsp:set!`, since that would be setting the DSP callback again.

To me, this seems to be a design problem with the sharedsystem — I can’t change some parts of its DSP function (since that would entail re-setting the DSP callback), and hence I can’t add any instruments of my own. Is there any way of resolving this? I can think of a few, although I’m not sure how well any of them would work:

- I may be doing something wrong in my attempt above to add another instrument — I’m not too familiar with Extempore yet. If so, there may be a way of adding another instrument which does not give this error.
- It may be possible to combine `dspmt`, `dsp1`, `dsp2` etc. into a single DSP function, which I could then modify to add another instrument without needing to re-set the DSP callback. If possible (although I’m not sure if it is), this seems like the simplest solution to me.
- One approach I was thinking of was to alter `make-instrument` so that it records every instrument created in a mutable list `*instruments*`. Then `dsp1`, `dsp2` etc. could all be replaced by a single function `dsp-all-instruments`, which iterates through `*instruments*`, does appropriate calculations for each instrument, and then adds them together, to get a DSP function which automatically includes every instrument which has been created. This approach would be the easiest for the user, as it doesn’t even require re-evaluation of the DSP function when making a new instrument; I can also see the maintenance of an `*instruments*` list as being useful even when not using the sharedsystem (e.g. `dsp-all-instruments` seems pretty useful for any sort of livecoding). On the other hand, it requires the modification of code outside the sharedsystem (specifically `make-instrument`) so make it work, and I’m not sure how easy to implement `dsp-all-instruments` would be.

**Comment by digego** [comment]
You can run as many instrument per dsp function as you like - at least as many as your cpu will support.  So, for example, change dsp1 from:

(set! out (syn1 in time chan dat))

to 

(set! out (+ (syn1 in time chan dat) (mysynth in time chan dat)))

you can make this change on-the-fly no problem.  then when you need another instrument on-the-fly add it to dsp2 then 3 then 4 then 5 then back to 1 etc.. i.e. balance is the key.  Now also important to point out is that not all instruments use the same compute power - you will be able to run about 5-10 samplers for the cost of 1 analogue synth.  Getting that balance right will require a bit of trial and error.  

So while you can't "add" more dsp functions, you can recompile the ones that are there, which is all you need to add more instruments on-the-fly.

A little more information.  dspmt is specifically for multi-threaded execution - and it is for that reason that there are multiple dsp functions.  Single threaded behaviour only requires 1 dsp function - and no aggregator.   That's what happens when you call (dsp:set! dsp) - it takes only a single dsp function that does everything.  You could easily implement your "dsp-all-instruments" that way - but only running on 1 cpu core.

In order to maximize performance on multi-core systems dspmt supports multiple dsp functions to distribute the load - but yes, you have to decide on the number of "cores" you want to use at the start of your session.  In an idealized sense there would be 1 dsp function per hyperthread saving 1 for the dspmt aggregate summation function.  So on my 12core AMD I might choose to run dsp(1-23) + dspmt.

five really was just a number picked out of a hat for the standardsystem. Something that I thought would probably run ok on a 2 core 4 HT cpu (i.e. low end), but provide enough dsp "cores" to allow for people to expand with their own instruments.

Also worth pointing out that if you want to run more dsp functions than you need just make sure the body of the dsp simple returns 0.0  (i.e. does not work).  Then you can use it later in the session *if* you need it.

Cheers,
Andrew.

**Comment by digego** [comment]
sorry second last line should say: (i.e. does no work).  In other words all your dsp function "cores" need to be valid at startup, but they can be configured to do very little work by simply returning 0.0 (silence)

**Comment by bradrn** [comment]
Thanks for the quick and helpful response @digego! I didn’t realise that I could recompile the `dsp` functions already there — I thought I had to have one function per instrument when using `dsp:set!` with multiple arguments. (Maybe it’s worth documenting that somewhere.)

**Comment by digego** [comment]
no worries, you can also recomplile dspmt whenever you like - you just can't call (dsp:set! ...) more than once in a session.

**Comment by bradrn** [comment]
> you can also recomplile dspmt whenever you like

I did realise this actually — you’ll see in my first post that I mentioned recompiling dspmt as part of my attempted solution. My issue was that I thought I could only add another instrument by calling `dsp:set!` more than once, which I can’t do.

Also, do you think it’s worth documenting how to use `dsp:set!` somewhere? The reference only mentions how to do it with one argument, but the sharedsystem code uses multiple arguments, which don’t seem to be documented anywhere. And if there were some documentation, then maybe it would avoid any more simple issues like this.

**Comment by digego** [comment]
No doubt - pull requests welcome :)

**Comment by bradrn** [comment]
> No doubt - pull requests welcome :)

I’d happily make one, but I’m not at all familiar with the syntax of `dsp:set!` (which was the cause of this issue). I know that `(dsp:set! fn)` sets the DSP function to `fn`, and I now know that `(dsp:set! #f dspmt f g ...)` runs `f`, `g`, … on separate “cores” and then combines the results with `dspmt`, but I’m not sure if there’s any other way to use it, or even if my descriptions above are at all correct.
