### ISSUE TITLE
scale function?

### ISSUE THREAD

**Issue by cmaughan** [digego/extempore#391]
In this demo: https://www.youtube.com/watch?v=rd1_nybU6kM&t=200s
there is the line:

(scale 3 8 (random '(-1 0 1 2)))

I get that 3, 8 is octave and number of notes, but I'm not following what third argument does.  I thought maybe it was selecting scale notes, but when I try it, it doesn't appear to be doing that...

**Comment by cmaughan** [comment]
After watching the video again, I suspect that the (-1 0 1 2) are adjustments to the Scale octave, with 0 meaning 'don't play'?  The github repo doesn't appear to work that way though.

**Comment by digego** [comment]
Hi Chris,

Note that the scale function in the screencast is an extension of the one
in github - so that's probably what has you confused.

So the way the screencast version of scale works is that you can provide a
stepsize.  The stepsize then defines how many steps to move up or down
through the 'scale' when choosing the next "note" (positive 'up' or
negative 'down' - or 0 for no steps to stay on a single pitch).  So the
default behaviour of (scale 4 8) is equivalent to (scale 4 8 1).   Starting
at octave 4 and moving 'down' by an octave one step at a time would be
(scale 4 8 -1).  Moving up in 2s (scale 4 8 2) etc..   (scale 4 8 0) would
give 8 * 60.

Hope that explains it for you :)

FYI below is my implementation for you to try (i'll also push this to git)
- also note the globally defined *scale*.

(define get-scale-stepsize
  (lambda (args)
    (cond ((null? args) 1)
          ((number? (car args)) (car args))
          ((null? (cdr args)) 1)
          ((number? (cadr args)) (cadr args))
          (else 1))))

(define get-scale-scale
  (lambda (args)
    (map (lambda (pitch) (modulo pitch 12))
         (cond ((null? args) *scale*)
               ((list? (car args)) (car args))
               ((null? (cdr args)) *scale*)
               ((list? (cadr args)) (cadr args))
               (else *scale*)))))

(define scale
  (lambda (octave num . args)
    (let ((stepsize (get-scale-stepsize args))
          (scale (get-scale-scale args)))
      (map (lambda (x)
             (pc:relative (+ 12 (car scale) (* 12 octave)) (* x stepsize)
scale))
           (range 0 num)))))

**Comment by digego** [comment]
Also, just FYI, stepsize is a real so 1.5 etc..   I mention this because
it's very useful :)

**Comment by cmaughan** [comment]
Thanks very much for the explanation, this makes perfect sense :)
