### ISSUE TITLE
pc:make-chord-fixed can't take symbols

### ISSUE THREAD

**Issue by lambdamusic** [digego/extempore#399]
Is this by design ? 

Eg this fails:

```
(define *notes* '(c3 g3 b3))

(let ((a (car *notes*)))
        (pc:make-chord a 90 8 '(0 3 5 6 7)))

;Trace: 
;function(round): argument 1 must be: number
;argument values: (c3) #<PROC round>
;Trace: pc:make-chord

```

It'd work simply by passing `(eval a)` to pc:make-chord.

Looks like the culprit is `round` that only takes integers.

**Comment by benswift** [comment]
Hey @lambdamusic , I think the confusion comes from the fact that the `c3` ([SPN](https://en.wikipedia.org/wiki/Scientific_pitch_notation)) symbols are bound to the corresponding midi note numbers, but as above you're still passing the symbol `c3` rather than the number.

This will do what you want:

```scheme
(define *notes* (list c3 g3 b3))

(let ((a (car *notes*)))
  (pc:make-chord a 90 8 '(0 3 5 6 7)))
```

Note that by using `list` above `*notes*` is no longer a list of symbols, but a list of numbers.

**Comment by lambdamusic** [comment]
Thanks! My bad - I totally missed the fact I was passing a quoted list..
